#!/usr/bin/env bash
# Description: 
#   This Script get/update lastest uTLGBotLib Arduino sources from full library
#   (https://github.com/J-Rios/uTLGBotLib)

echo ""
echo " Trying to get/update uTLGBotLib Arduino sources from lastest."
echo ""

echo " Downloading full uTLGBotLib repository..."
rm -rf uTLGBotLib
git clone --recurse-submodules https://github.com/J-Rios/uTLGBotLib
if [[ $? != 0 ]]; then
    echo "   Error: Can't clone uTLGBotLib library."
    echo ""
    exit 1
fi

echo " Removing mbedtls and jsmn no necesary files."
rm -rf ./uTLGBotLib/lib/multihttpsclient/mbedtls
rm -rf ./uTLGBotLib/lib/jsmn/example
rm -rf ./uTLGBotLib/lib/jsmn/test

echo " Copying specific sources files into expected locations..."
rm -rf ../Arduino_uTLGBotLib/src/*
mkdir -p ../Arduino_uTLGBotLib/src/utility

cp -a ./uTLGBotLib/lib/jsmn ../Arduino_uTLGBotLib/src/utility/
cp -a ./uTLGBotLib/lib/multihttpsclient ../Arduino_uTLGBotLib/src/utility/
cp -a ./uTLGBotLib/src/tlgcert.h ../Arduino_uTLGBotLib/src/
cp -a ./uTLGBotLib/src/utlgbotlib.* ../Arduino_uTLGBotLib/src/

echo " Replacing #include jsmn/multihttpsclient in utlgbotlib.h..."
sed -i "s/#include \"multihttpsclient.h\"/#include \"utility\/multihttpsclient\/multihttpsclient.h\"/" ../Arduino_uTLGBotLib/src/utlgbotlib.h
sed -i "s/#include \"jsmn.h\"/#include \"utility\/jsmn\/jsmn.h\"/" ../Arduino_uTLGBotLib/src/utlgbotlib.h

echo " Removing full cloned uTLGBotLib and clean..."
rm -rf uTLGBotLib

echo ""
echo " Process completed."

exit 0
